version: '3.4'

networks:
  mantle: {}

x-base: &base
  restart: unless-stopped
  networks:
    mantle: {}

services:
  l1_chain:
    <<: *base
    container_name: bitl1chain
    deploy: # run switch
      replicas: 0

  deployer:
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.packages
      target: deployer
    image: mantlenetworkio/deployer:${DOCKER_TAG_DEPLOYER:-latest}
    entrypoint: ./deployer.sh
    <<: *base
    container_name: mantledeployer
    environment:
      CONTRACTS_RPC_URL: ${CONTRACTS_RPC_URL:-https://goerli.infura.io/v3/d6167662f2104fbc8d5a947e59dbaa28}
      CONTRACTS_DEPLOYER_KEY: ${CONTRACTS_DEPLOYER_KEY:-04586afc8e720e5dbb06f598b056d835bb02cd9743efd438cda8055c90722f33}
      CONTRACTS_TARGET_NETWORK: ${CONTRACTS_TARGET_NETWORK:-goerli-qa}
      ETHERSCAN_API_KEY: ${ETHERSCAN_API_KEY:-B1XAN986315AME96W9QK7X1RGQ6WJMWEPW}
      BVM_SEQUENCER_ADDRESS: ${BVM_SEQUENCER_ADDRESS:-}
      BVM_PROPOSER_ADDRESS: ${BVM_PROPOSER_ADDRESS:-}
      SKIP_CONTRACT_DEPLOY: ${SKIP_CONTRACT_DEPLOY:-YES}
      BVM_BLOCK_SIGNER_ADDRESS: ${BVM_BLOCK_SIGNER_ADDRESS:-}
      BVM_FEE_WALLET_ADDRESS: ${BVM_FEE_WALLET_ADDRESS:-}
      BVM_ADDRESS_MANAGER_OWNER: ${BVM_ADDRESS_MANAGER_OWNER:-}
      BVM_GAS_PRICE_ORACLE_OWNER: ${BVM_GAS_PRICE_ORACLE_OWNER:-}
      AUTOMATICALLY_TRANSFER_OWNERSHIP: ${AUTOMATICALLY_TRANSFER_OWNERSHIP:-true}
      L1_BIT_ADDRESS: ${L1_BIT_ADDRESS:-0x320735F74BaA37Bc344a96D4A4EfABBAB06A522C}
    ports:
      # expose the service to the host for getting the contract addrs
      - ${DEPLOYER_PORT:-8080}:8081


  dtl:
    <<: *base
    container_name: bitdtl
    environment:
      DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: ${DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT:-https://goerli.infura.io/v3/d6167662f2104fbc8d5a947e59dbaa28}
      DATA_TRANSPORT_LAYER__L1_START_HEIGHT: ${DATA_TRANSPORT_LAYER__L1_START_HEIGHT:-7759200}
      DATA_TRANSPORT_LAYER__L2_CHAIN_ID: ${DATA_TRANSPORT_LAYER__L2_CHAIN_ID:-1705003}

  l2geth:
    <<: *base
    environment:
      ETH1_HTTP: ${ETH1_HTTP:-https://goerli.infura.io/v3/d6167662f2104fbc8d5a947e59dbaa28}
    container_name: bitl2geth

  gas_oracle:
    <<: *base
    container_name: bitgasoracle
    env_file:
      - ./envs/gas-oracle.env
    environment:
      GAS_PRICE_ORACLE_ETHEREUM_HTTP_URL: ${GAS_PRICE_ORACLE_ETHEREUM_HTTP_URL:-https://goerli.infura.io/v3/d6167662f2104fbc8d5a947e59dbaa28}
      TOKEN_PRICER_UPDATE_FREQUENCY: ${TOKEN_PRICER_UPDATE_FREQUENCY:-600}
    deploy:
      replicas: 1

  batch_submitter:
    <<: *base
    container_name: bitbatchsubmitter
    environment:
      L1_ETH_RPC: ${L1_ETH_RPC:-https://goerli.infura.io/v3/d6167662f2104fbc8d5a947e59dbaa28}

  integration_tests:
    <<: *base
    container_name: bititests
    deploy:
      replicas: 0

  relayer:
    container_name: bitrelayer
    deploy:
      replicas: 0

  verifier:
    <<: *base
    container_name: bitverifier
    environment:
      ETH1_HTTP: ${ETH1_HTTP:-https://goerli.infura.io/v3/d6167662f2104fbc8d5a947e59dbaa28}
    deploy:
      replicas: 1

  replica:
    <<: *base
    container_name: bitreplica
    deploy:
      replicas: 0

  replica_healthcheck:
    <<: *base
    container_name: bitreplicahealthcheck
    deploy:
      replicas: 0

  fault_detector:
    <<: *base
    container_name: bitfaultdetector
    deploy:
      replicas: 0

  l2geth2:
    <<: *base
    container_name: bitl2geth2
    deploy:
      replicas: 0  # disable by default

