[Node.P2P]
MaxPeers = 10
NoDiscovery = true
StaticNodes = ["enode://09998ab210032351a2bea94fbb8c867cfc95553019d3cecfe0d3f3aef78b24290e624b07a99fdaa3c2fb9015d193303179b396e3520284d249ef9a233a5f5e62@127.0.0.1:30303?discport=0"]
ListenAddr = ":30323"
EnableMsgEvents = false
