version: '3.4'

networks:
  mantle: { }

x-base: &base
  restart: unless-stopped
  networks:
    mantle: { }

services:
  l1_chain:
    <<: *base
    container_name: bitl1chain
    deploy: # run switch
      replicas: 0

  deployer:
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.packages
      target: deployer
    image: mantlenetworkio/deployer:${DOCKER_TAG_DEPLOYER:-latest}
    entrypoint: ./deployer.sh
    <<: *base
    container_name: mantledeployer
    environment:
      CONTRACTS_RPC_URL: ${CONTRACTS_RPC_URL:-https://eth-goerli.g.alchemy.com/v2/821_LFssCCQnEG3mHnP7tSrc87IQKsUp}
      CONTRACTS_DEPLOYER_KEY: ${CONTRACTS_DEPLOYER_KEY:-114983389b91256e6e26cb0e30371ceb5385e3fb309cd0e7823b86fff27c9ba4}
      CONTRACTS_TARGET_NETWORK: ${CONTRACTS_TARGET_NETWORK:-goerli-qa}
      ETHERSCAN_API_KEY: ${ETHERSCAN_API_KEY:-B1XAN986315AME96W9QK7X1RGQ6WJMWEPW}
      BVM_SEQUENCER_ADDRESS: ${BVM_SEQUENCER_ADDRESS:-}
      BVM_PROPOSER_ADDRESS: ${BVM_PROPOSER_ADDRESS:-}
      SKIP_CONTRACT_DEPLOY: ${CONTRACTS_DEPLOYER_KEY:-YES}
      BVM_BLOCK_SIGNER_ADDRESS: ${BVM_BLOCK_SIGNER_ADDRESS:-}
      BVM_FEE_WALLET_ADDRESS: ${BVM_FEE_WALLET_ADDRESS:-}
      BVM_ADDRESS_MANAGER_OWNER: ${BVM_ADDRESS_MANAGER_OWNER:-}
      BVM_GAS_PRICE_ORACLE_OWNER: ${BVM_GAS_PRICE_ORACLE_OWNER:-}
      AUTOMATICALLY_TRANSFER_OWNERSHIP: ${AUTOMATICALLY_TRANSFER_OWNERSHIP:-true}
      L1_BIT_ADDRESS: ${L1_BIT_ADDRESS:-0x1A4b46696b2bB4794Eb3D4c26f1c55F9170fa4C5}
    ports:
      # expose the service to the host for getting the contract addrs
      - ${DEPLOYER_PORT:-8080}:8081


  dtl:
    <<: *base
    container_name: bitdtl
    environment:
      DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: ${DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT:-https://eth-goerli.g.alchemy.com/v2/821_LFssCCQnEG3mHnP7tSrc87IQKsUp}
      DATA_TRANSPORT_LAYER__L1_START_HEIGHT: ${DATA_TRANSPORT_LAYER__L1_START_HEIGHT:-7742200}
      DATA_TRANSPORT_LAYER__L2_CHAIN_ID: ${DATA_TRANSPORT_LAYER__L2_CHAIN_ID:-1705003}

  l2geth:
    <<: *base
    environment:
      ETH1_HTTP: ${ETH1_HTTP:-https://eth-goerli.g.alchemy.com/v2/821_LFssCCQnEG3mHnP7tSrc87IQKsUp}
    container_name: bitl2geth

  gas_oracle:
    <<: *base
    container_name: bitgasoracle
    environment:
      GAS_PRICE_ORACLE_ETHEREUM_HTTP_URL: ${GAS_PRICE_ORACLE_ETHEREUM_HTTP_URL:-https://eth-goerli.g.alchemy.com/v2/821_LFssCCQnEG3mHnP7tSrc87IQKsUp}
      GAS_PRICE_ORACLE_PRIVATE_KEY: ${GAS_PRICE_ORACLE_PRIVATE_KEY:-0x114983389b91256e6e26cb0e30371ceb5385e3fb309cd0e7823b86fff27c9ba4}
    deploy:
      replicas: 1

  batch_submitter:
    <<: *base
    container_name: bitbatchsubmitter
    environment:
      L1_ETH_RPC: ${L1_ETH_RPC:-https://eth-goerli.g.alchemy.com/v2/821_LFssCCQnEG3mHnP7tSrc87IQKsUp}
      BATCH_SUBMITTER_SEQUENCER_PRIVATE_KEY: ${BATCH_SUBMITTER_SEQUENCER_PRIVATE_KEY:-0x114983389b91256e6e26cb0e30371ceb5385e3fb309cd0e7823b86fff27c9ba4}
      BATCH_SUBMITTER_PROPOSER_PRIVATE_KEY: ${BATCH_SUBMITTER_PROPOSER_PRIVATE_KEY:-0x5ef80d706bea918cb4592c4ad9724dbaf9c3818494aa6f4e0803a03013d0a5f4}
  subsidy:
    <<: *base
    container_name: bitsubsidy
    environment:
      SUBSIDY_ETHEREUM_HTTP_URL: ${SUBSIDY_ETHEREUM_HTTP_URL:-https://eth-goerli.g.alchemy.com/v2/821_LFssCCQnEG3mHnP7tSrc87IQKsUp}
      SUBSIDY_PAYER_PRIVATE_KEY: ${SUBSIDY_PAYER_PRIVATE_KEY:-0x114983389b91256e6e26cb0e30371ceb5385e3fb309cd0e7823b86fff27c9ba4}
      SUBSIDY_SCC_ADDRESS: ${SUBSIDY_SCC_ADDRESS:-}
      SUBSIDY_CTC_ADDRESS: ${SUBSIDY_CTC_ADDRESS:-}
      SUBSIDY_L1_QUERY_EPOCH_LENGTH_SECONDS: ${SUBSIDY_L1_QUERY_EPOCH_LENGTH_SECONDS:-}
      SUBSIDY_START_BLOCK: ${SUBSIDY_START_BLOCK:-}

    deploy:
      replicas: 1
  integration_tests:
    <<: *base
    container_name: bititests
    deploy:
      replicas: 0

  relayer:
    container_name: bitrelayer
    deploy:
      replicas: 0

  verifier:
    <<: *base
    container_name: bitverifier
    deploy:
      replicas: 0

  replica:
    <<: *base
    container_name: bitreplica
    deploy:
      replicas: 0

  replica_healthcheck:
    <<: *base
    container_name: bitreplicahealthcheck
    deploy:
      replicas: 0

  fault_detector:
    <<: *base
    container_name: bitfaultdetector
    deploy:
      replicas: 0

  l2geth2:
    <<: *base
    container_name: bitl2geth2
    deploy:
      replicas: 0  # disable by default

