version: '3.4'

networks:
  mantle:
    driver: bridge
    ipam:
     config:
       - subnet: 172.5.0.0/16
         gateway: 172.5.0.1

x-base: &base
  restart: unless-stopped
  networks:
    mantle: {}

x-base-env: &base-env
  TSS_NODE_BASE_DIR: /data/tssnode
  TSS_NODE_DB_DIR: /data/tssnode/db
  TSS_NODE_L1_URL: http://l1_chain:8545
  TSS_NODE_L2_ETH_RPC: http://l2geth:8545

services:
  l1_chain:
    <<: *base
    container_name: bitl1chain
    deploy: # run switch
      replicas: 1

  deployer:
    <<: *base
    container_name: bitdeployer
    environment:
      CONTRACTS_RPC_URL: ${CONTRACTS_RPC_URL:-http://l1_chain:8545}
      CONTRACTS_DEPLOYER_KEY: ${CONTRACTS_DEPLOYER_KEY:-0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97}
      CONTRACTS_TARGET_NETWORK: ${CONTRACTS_TARGET_NETWORK:-local}
      BVM_SEQUENCER_ADDRESS: ${BVM_SEQUENCER_ADDRESS:-}
      BVM_PROPOSER_ADDRESS: ${BVM_PROPOSER_ADDRESS:-}
      BVM_BLOCK_SIGNER_ADDRESS: ${BVM_BLOCK_SIGNER_ADDRESS:-}
      BVM_FEE_WALLET_ADDRESS: ${BVM_FEE_WALLET_ADDRESS:-}
      BVM_ADDRESS_MANAGER_OWNER: ${BVM_ADDRESS_MANAGER_OWNER:-}
      BVM_GAS_PRICE_ORACLE_OWNER: ${BVM_GAS_PRICE_ORACLE_OWNER:-}
      L1_BIT_ADDRESS: ${L1_BIT_ADDRESS:-0x1A4b46696b2bB4794Eb3D4c26f1c55F9170fa4C5}

  dtl:
    <<: *base
    container_name: bitdtl

  l2geth:
    <<: *base
    container_name: bitl2geth

  gas_oracle:
    <<: *base
    container_name: bitgasoracle
    deploy:
      replicas: 1

  batch_submitter:
    <<: *base
    container_name: bitbatchsubmitter

  integration_tests:
    <<: *base
    container_name: bititests
    deploy:
      replicas: 0

  relayer:
    <<: *base
    container_name: bitrelayer
    deploy:
      replicas: 1

  verifier:
    <<: *base
    container_name: bitverifier
    deploy:
      replicas: 0

  replica:
    <<: *base
    container_name: bitreplica
    deploy:
      replicas: 0

  replica_healthcheck:
    <<: *base
    container_name: bitreplicahealthcheck
    deploy:
      replicas: 0

  fault_detector:
    <<: *base
    container_name: bitfaultdetector
    deploy:
      replicas: 1

  l2geth2:
    <<: *base
    container_name: bitl2geth2
    deploy:
      replicas: 0  # disable by default

  tss-manager:
    <<: *base
    depends_on:
      - l2geth
    image: mantlenetworkio/tss:latest
    environment:
      TSS_L1_URL: http://l1_chain:8545
      TSS_L1_CONFIRM_BLOCKS: 0
      TSS_L1_RECEIPT_CONFIRM_TIMEOUT: 30s
      TSS_SCC_CONTRACT_ADDRESS: 0xd9e2F450525079e1e29fB23Bc7Caca6F61f8fD4a
      TSS_TSS_GROUP_CONTRACT_ADDRESS: 0x36fCf02Fc651c0b7ef2ECA446Dd2405364F85337
      TSS_TSS_STAKING_SLASH_CONTRACT_ADDRESS: 0xa83239cf2b900682001f9144144B5E5e5788A631
      TSS_SIGNED_BATCHES_WINDOW: 5
      TSS_MIN_SIGNED_IN_WINDOW: 2
    build:
      context: ..
      dockerfile: ./ops/docker/tss/Dockerfile
      target: tss
    command: ./tss manager -c config/tss-manager-config.toml
    volumes:
      - ./data/tss-manager:/root/tss-manager/db
      - ./config:/app/config
  tss-1:
    depends_on:
      - tss-manager
    image: mantlenetworkio/tss:latest
    build:
      context: ..
      dockerfile: ./ops/docker/tss/Dockerfile
      target: tss
    environment:
      <<: *base-env
      TSS_NODE_PRIVATE_KEY: 8579041c09247ea30aa30fdc4aad1897505ecfe44b92dc01c6481fae7d5dc705
      TSS_NODE_BOOTSTRAP_PEERS: >
        /ip4/172.5.0.12/tcp/8000/p2p/16Uiu2HAmBKgEjv9buq3LkSHrRRcTN3c5VbPskgaqwq6mRquHJvk4,
        /ip4/172.5.0.13/tcp/8000/p2p/16Uiu2HAmC3L4WmoJHcXhFtXDfg6BMcdweybEeLhfUtKMi4WhxViH,
        /ip4/172.5.0.14/tcp/8000/p2p/16Uiu2HAkwMunZrRiXKWJesEakL8UnrUQSR3sRVGve6HjYxdQnUZv
      TSS_NODE_EXTERNAL_IP: 172.5.0.11
    command: ./tss node -c config/tss-node-config.toml
    volumes:
      - ./data/tss-1:/data
      - ./config:/app/config
    networks:
      mantle:
        ipv4_address: 172.5.0.11

  tss-2:
    depends_on:
      - tss-1
    image: mantlenetworkio/tss:latest
    build:
      context: ..
      dockerfile: ./ops/docker/tss/Dockerfile
      target: tss
    command: ./tss node -c config/tss-node-config.toml
    environment:
      <<: *base-env
      TSS_NODE_PRIVATE_KEY: 2bdfd71614eb0d2a994ecd96ba5f1dc9774e13ccdaece910992e4818e823e822
      TSS_NODE_BOOTSTRAP_PEERS: >
        /ip4/172.5.0.11/tcp/8000/p2p/16Uiu2HAmQWNYM7JXW55Qs5z6mR49eVu5pdRk17dKZ6zRSscdcWve,
        /ip4/172.5.0.13/tcp/8000/p2p/16Uiu2HAmC3L4WmoJHcXhFtXDfg6BMcdweybEeLhfUtKMi4WhxViH,
        /ip4/172.5.0.14/tcp/8000/p2p/16Uiu2HAkwMunZrRiXKWJesEakL8UnrUQSR3sRVGve6HjYxdQnUZv
      TSS_NODE_EXTERNAL_IP: 172.5.0.12
    volumes:
      - ./data/tss-2:/data
      - ./config:/app/config
    networks:
      mantle:
        ipv4_address: 172.5.0.12

  tss-3:
    depends_on:
      - tss-1
      - tss-2
    image: mantlenetworkio/tss:latest
    build:
      context: ..
      dockerfile: ./ops/docker/tss/Dockerfile
      target: tss
    command: ./tss node -c config/tss-node-config.toml
    environment:
      <<: *base-env
      TSS_NODE_PRIVATE_KEY: ad55949cb6419c86cd59fb7b36a3d86d4dd7ee9cae5c55d2fd9584c80ea5bacb
      TSS_NODE_BOOTSTRAP_PEERS: >
        /ip4/172.5.0.11/tcp/8000/p2p/16Uiu2HAmQWNYM7JXW55Qs5z6mR49eVu5pdRk17dKZ6zRSscdcWve,
        /ip4/172.5.0.12/tcp/8000/p2p/16Uiu2HAmBKgEjv9buq3LkSHrRRcTN3c5VbPskgaqwq6mRquHJvk4,
        /ip4/172.5.0.14/tcp/8000/p2p/16Uiu2HAkwMunZrRiXKWJesEakL8UnrUQSR3sRVGve6HjYxdQnUZv
      TSS_NODE_EXTERNAL_IP: 172.5.0.13
    volumes:
      - ./data/tss-3:/data
      - ./config:/app/config
    networks:
      mantle:
        ipv4_address: 172.5.0.13

  tss-4:
    depends_on:
      - tss-1
      - tss-2
      - tss-3
    image: mantlenetworkio/tss:latest
    build:
      context: ..
      dockerfile: ./ops/docker/tss/Dockerfile
      target: tss
    command: ./tss node -c config/tss-node-config.toml
    environment:
      <<: *base-env
      TSS_NODE_PRIVATE_KEY: a7e87580b54050212e20ab75fb808ec9c7f759201ec4fe9ea1acad85adaf9b52
      TSS_NODE_BOOTSTRAP_PEERS: >
        /ip4/172.5.0.11/tcp/8000/p2p/16Uiu2HAmQWNYM7JXW55Qs5z6mR49eVu5pdRk17dKZ6zRSscdcWve,
        /ip4/172.5.0.12/tcp/8000/p2p/16Uiu2HAmBKgEjv9buq3LkSHrRRcTN3c5VbPskgaqwq6mRquHJvk4,
        /ip4/172.5.0.13/tcp/8000/p2p/16Uiu2HAmC3L4WmoJHcXhFtXDfg6BMcdweybEeLhfUtKMi4WhxViH
      TSS_NODE_EXTERNAL_IP: 172.5.0.14
    volumes:
      - ./data/tss-4:/data
      - ./config:/app/config
    networks:
      mantle:
        ipv4_address: 172.5.0.14
