version: '3.4'

networks:
  mantle: {}

x-base: &base
  restart: unless-stopped
  networks:
    mantle: {}

services:
  l1_chain:
    <<: *base
    container_name: bitl1chain
    deploy: # run switch
      replicas: 1

  deployer:
    <<: *base
    container_name: bitdeployer
    environment:
      CONTRACTS_RPC_URL: ${CONTRACTS_RPC_URL:-http://l1_chain:8545}
      CONTRACTS_DEPLOYER_KEY: ${CONTRACTS_DEPLOYER_KEY:-ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}
      CONTRACTS_TARGET_NETWORK: ${CONTRACTS_TARGET_NETWORK:-local}
      BVM_SEQUENCER_ADDRESS: ${BVM_SEQUENCER_ADDRESS:-}
      BVM_PROPOSER_ADDRESS: ${BVM_PROPOSER_ADDRESS:-}
      BVM_BLOCK_SIGNER_ADDRESS: ${BVM_BLOCK_SIGNER_ADDRESS:-}
      BVM_FEE_WALLET_ADDRESS: ${BVM_FEE_WALLET_ADDRESS:-}
      BVM_ADDRESS_MANAGER_OWNER: ${BVM_ADDRESS_MANAGER_OWNER:-}
      BVM_GAS_PRICE_ORACLE_OWNER: ${BVM_GAS_PRICE_ORACLE_OWNER:-}
      L1_BIT_ADDRESS: ${L1_BIT_ADDRESS:-0x1A4b46696b2bB4794Eb3D4c26f1c55F9170fa4C5}

  dtl:
    <<: *base
    container_name: bitdtl

  scheduler:
    <<: *base
    container_name: bitscheduler

  gas_oracle:
    <<: *base
    container_name: bitgasoracle
    deploy:
      replicas: 0

  batch_submitter:
    <<: *base
    container_name: bitbatchsubmitter

  sequencer1:
    <<: *base
    container_name: bitsequencer1
    deploy:
      replicas: 1

  sequencer2:
    <<: *base
    container_name: bitsequencer2
    deploy:
      replicas: 1

  replica1:
    <<: *base
    container_name: bitreplica1
    deploy:
      replicas: 1

  replica2:
    <<: *base
    container_name: bitreplica2
    deploy:
      replicas: 1

  verifier:
    <<: *base
    container_name: bitverifier
    deploy:
      replicas: 1

  replica_healthcheck:
    <<: *base
    container_name: bitreplicahealthcheck
    deploy:
      replicas: 0

  fault_detector:
    <<: *base
    container_name: bitfaultdetector
    deploy:
      replicas: 0

  relayer:
    <<: *base
    container_name: bitrelayer
    deploy:
      replicas: 0

  integration_tests:
    <<: *base
    container_name: bititests
    deploy:
      replicas: 0

